---
argument_specs:
  main:
    short_description: Setup users for Mastodon app server
    description:
      - Setup users for Mastodon app server
    author:
      - guskma
    options:
      mastodon_app_user_name:
        type: str
        required: false
        default: mastodon
        description:
          - Username to execute Mastodon application.
          - Execute application processes (web, sidekiq, streaming, and other...)
          - Defaults `mastodon`
      mastodon_app_user_password:
        type: str
        required: false
        default:
        description:
          - Password to execute Mastodon application.
          - This parameter does not need to be set by default.
          - Used to login to administer the server.
      mastodon_app_user_is_admin:
        type: bool
        required: false
        default: false
        description:
          - The user is granted administrative privileges.
          - If set to `true`, the `sudo` command can be executed.
          - This parameter does not need to be set by default.
          - Used to login to administer the server.
