---
- name: Generate secrets from command
  ansible.builtin.set_fact:
    __rails_secrets: "{{ lookup('ansible.builtin.pipe', 'cat /dev/urandom | base64 | head -n 2') | ansible.builtin.split('\n') }}"

- name: Generate VEPID key
  environment:
    RBENV_ROOT: "{{ mastodon_app_anyenv_path }}/envs/rbenv"
    RBENV_SHELL: "bash"
    RAILS_ENV: "{{ mastodon_app_environment }}"
  ansible.builtin.command:
    cmd: "{{ mastodon_app_anyenv_path }}/envs/rbenv/shims/bundle exec rake mastodon:webpush:generate_vapid_key"
  args:
    chdir: "{{ mastodon_app_path }}"
  changed_when: false
  register: __vapid_key
