---
- name: Add an Apt signing key, uses whichever key is at the URL
  become: true
  ansible.builtin.apt_key:
    url: "{{ __mastodon_db_aptkey_url }}"
    state: present

- name: Add postgresql repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: postgresql

- name: Install apt packages (postgresql)
  become: true
  ansible.builtin.apt:
    name: "{{ __mastodon_apt_db_packages }}"
    state: present
