---
argument_specs:
  main:
    short_description: Setup Mastodon app repository.
    description:
      - Setup Mastodon app repository.
    author:
      - guskma
    options:
      mastodon_app_version:
        type: str
        required: true
        description:
          - Specified Mastodon app version.
      mastodon_app_path:
        type: str
        required: false
        default: /home/mastodon/live
        description:
          - Mastodon app root directory (absolute path).
      mastodon_app_user_name:
        type: str
        required: false
        default: mastodon
        description:
          - Username to execute Mastodon application.
          - Execute application processes (web, sidekiq, streaming, and other...)
          - Defaults `mastodon`
      mastodon_app_repository:
        type: str
        required: false
        default: https://github.com/mastodon/mastodon.git
        description:
          - Mastodon app repository's URL.
